expression = {
  (transaction) ~ ("," ~ transaction)+?
}

transaction = {
  amount
  ~ keyword
  ~ ("@" ~ payee_key | "!" ~ modifier | "$" ~ tags)+?
  ~ ( WHITESPACE? ~ ":" ~ WHITESPACE? ~ payee_name)?
}

amount = { ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }

keyword = { ASCII_ALPHANUMERIC+ }
payee_key = { ASCII_ALPHANUMERIC+ }
modifier = @{ ASCII_ALPHANUMERIC+ }
tags = @{ ASCII_ALPHANUMERIC+ }
payee_name = { ASCII_ALPHANUMERIC+ }

WHITESPACE = _{ " " }
